# 13. Numpy

A library for Python, NumPy lets you work with huge, multidimensional matrices and arrays.

Along with that, it provides a gamut of high-level functions to perform mathematical operations on these structures.

The term ‘Numpy’ is a portmanteau of the words ‘NUMerical’ and ‘PYthon’.

### Features of Numpy

- NumPy stands on CPython, a non-optimizing bytecode interpreter.
- Multidimensional arrays.
- Functions and operators for these arrays.
- Python Alternative to MATLAB.
- ndarray- n-dimensional arrays.
- Fourier transforms and shapes manipulation.
- Linear algebra and random number generation.

### Import Numpy

In [1]:
import numpy as np

### Numpy ndarray

This is one of the most important features of numpy. ndarray is an n-dimensional array, a grid of values of the same kind.

A tuple of nonnegative integers indexes this tuple. An array’s rank is its number of dimensions.

In [2]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [3]:
a.shape      # (3,)-->1D

(3,)

In [4]:
a[0], a[2]

(1, 3)

In [5]:
a[1]=5
a

array([1, 5, 3])

Another example:

In [7]:
b = np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [8]:
b[0,1]

5

In [9]:
b.shape

(2, 3)

In [10]:
b.size

6

In [12]:
b[0,1]= 2
b

array([[4, 2, 6],
       [7, 8, 9]])

### Create NumPy Array

In [14]:
np.arange(7)  #this is like range in python

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
np.random.random((3,3))    #Fills random values

array([[0.97146497, 0.02186754, 0.06203961],
       [0.45613283, 0.1221603 , 0.53595702],
       [0.39903607, 0.67210078, 0.7479507 ]])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((1,2))

array([[0., 0.]])

In [19]:
np.eye(3)     # Identity matix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.full((3,2),7)  # Matrix of constants

array([[7, 7],
       [7, 7],
       [7, 7]])

In [25]:
np.empty([2,3])     # Empty array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.array([1,2,3], ndmin=4)   #minimum dimension

array([[[[1, 2, 3]]]])

In [28]:
np.array([1,2,3], dtype=complex)     #data type

array([1.+0.j, 2.+0.j, 3.+0.j])

### Numpy-Data Types

A NumPy array holds elements of the same kind.

If while creating a NumPy array, you do not specify the data type, NumPy will decide it for you.

The following data types-

bool_, int_, intc, intp, int8, int16, int32, int64, uint8, uint16, uint32, uint64, float_, float16, float32, float64, complex_, complex64, complex128

In [29]:
np.dtype(np.int32)

dtype('int32')

In [33]:
np.dtype('i4')

dtype('int32')

In [35]:
np.dtype('f8')

dtype('float64')

### Functions of NumPy Array

Converting from 2D to 1D array

In [86]:
from numpy import *
a = array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
b=a.flatten()    #2D to 1D
print(b)

[1 2 3 4 5 6]


In [36]:
a=np.array([[1,2,3],[4,5,6]])
a.reshape(3,2)                   

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a.ndim   #number of array dimensions 

2

In [38]:
np.array([[1,2,3],[4,5,6]]).itemsize     #Length of each element in bytes

4

In [42]:
np.array([[1,2,3],[4,5,6]],dtype=np.int8).itemsize

1

In [45]:
np.array([[1.,2.,3.],[4.,5.,6.]],dtype=np.float16).itemsize

2

In [46]:
a.flags              #REFER- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [88]:
from numpy import *
m = matrix('1 2 3; 4 5 6; 7 8 9')     #2D matrix
print (m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [89]:
diagonal(m)     # print diagonal elements

array([1, 5, 9])

In [92]:
m.max()

9

In [93]:
m.min()

1

### Numpy Array Indexing

In [48]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[:2, 1:3]
b

array([[2, 3],
       [5, 6]])

In [50]:
b= a[0:3, 0:2]
b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [51]:
a[1,2]

6

In [52]:
b[0,0]=36
a

array([[36,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [53]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [54]:
a[1:2, :]

array([[4, 5, 6]])

In [55]:
a[1:2, 2:3]

array([[6]])

In [56]:
a[:,1]

array([2, 5, 8])

In [57]:
a[:,0]

array([36,  4,  7])

#### 1. Integer Indexing
It is possible to create an array from another.

In [58]:
a= np.array([[1,2],[3,4],[5,6]])
a[[[0,1,2],[0,1,0]]]             #Prints elements at [0,0], [1,1], and [2,0]

C:\Users\DELL\AppData\Local\Temp/ipykernel_2544/1075112984.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a[[[0,1,2],[0,1,0]]]             #Prints elements at [0,0], [1,1], and [2,0]


array([1, 4, 5])

In [59]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
b

array([0, 2, 0, 1])

In [60]:
a[np.arange(4),b]

array([ 1,  6,  7, 11])

In [62]:
a[np.arange(4), b]+=10
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

#### 2. Boolean Indexing
It is possible to create an array from another.

In [63]:
a= np.array([[1,2],[3,4],[5,6]])
boolean=(a>3)
boolean

array([[False, False],
       [False,  True],
       [ True,  True]])

In [64]:
a[boolean]

array([4, 5, 6])

### Mathematical Functions on Arrays in NumPy

In [67]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.add(a,b)                           #a+b does the same

array([[ 8, 10, 12],
       [14, 16, 18]])

In [68]:
np.subtract(a,b)      #a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [69]:
np.multiply(a,b)       #a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [70]:
np.divide(a,b)        #a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [72]:
np.sqrt(a)            #square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [73]:
a=np.array([[1,2],[3,4]])
np.sum(a)

10

In [74]:
np.sum(a, axis=0)   #sum of each column

array([4, 6])

In [75]:
np.sum(a,axis=1)    #Sum of each row

array([3, 7])

In [76]:
a.T      #transpose the matrix

array([[1, 3],
       [2, 4]])

In [78]:
np.array([5,4,6]).T      

array([5, 4, 6])

Another Example:

In [81]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])

In [82]:
v.dot(w)                      #Same as np.dot(v,w)
                              #(9*11) + (10*12)=219

219

In [83]:
x.dot(v)

array([29, 67])

In [85]:
x.dot(y)                    # (1*5)+(2*7) =19, (1*6))+(2*8)=22
                            # (3*5)+(4*7) =43, (3*6)+(4*8)=50

array([[19, 22],
       [43, 50]])

In [94]:
m1 = matrix('1 2 3; 4 5 6; 7 8 9')
m2 = matrix('5 6 7; 2 1 8; 7 3 4')
m = m1*m2
print(m)

[[ 30  17  35]
 [ 72  47  92]
 [114  77 149]]
